# Generated by Django 2.1.2 on 2018-10-07 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('independent', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiposdeservicio',
            name='imagen',
            field=models.ImageField(null=True, upload_to='services'),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='photos'),
        ),
    ]
