# Generated by Django 2.1.2 on 2018-10-08 03:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('independent', '0002_auto_20181007_2006'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=1000)),
                ('correo', models.CharField(max_length=1000)),
                ('trabajador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='independent.Trabajador')),
            ],
        ),
    ]
